### PR TITLE
feat(config): allow spaces in IP ranges

### LINKED ISSUE #499: Whitespaces in 'addresses' configuration property
**The bug itself, as detailed as you can:**

When using this configuration ('config'), all works as expected:

```yaml
address-pools:

- name: ingress
  protocol: layer2
  addresses:
    - 10.0.0.80-10.0.0.80

- name: default
  protocol: layer2
  addresses:
    - 10.0.0.81-10.0.0.99
```
But when there are spaces, metallb is unable to provide an IP, so the EXTERNAL-IP keeps <pending>:

```yaml
address-pools:

- name: ingress
  protocol: layer2
  addresses:
    - 10.0.0.80 - 10.0.0.80

- name: default
  protocol: layer2
  addresses:
    - 10.0.0.81 - 10.0.0.99
```
The logs of the speaker shows the error:

```json
{
  "caller": "k8s.go:361",
  "configmap": "kube-metallb/config",
  "error": "parsing address pool #2: invalid CIDR \"10.0.0.81 - 10.0.0.99\" in pool \"default\"",
  "event": "configStale",
  "msg": "config (re)load failed, config marked stale",
  "ts": "2019-11-22T12:19:02.449737153Z"
}
```

**Version of MetalLB**
```
$ kubectl -n kube-metallb get pod -ojson | jq -r ".items[].spec.containers[].image"
metallb/controller:v0.8.2
metallb/speaker:v0.8.2
metallb/speaker:v0.8.2
```

**Version of Kubernetes**
```
$ kubectl version -ojson | jq -r ".serverVersion.gitVersion"`
v1.16.0
```

**Name and version of network addon (e.g. Calico, Weave...)**
```
$ kubectl -n kube-flannel get pod -ojson | jq -r ".items[].spec.containers[].image"
quay.io/coreos/flannel:v0.11.0-amd64
quay.io/coreos/flannel:v0.11.0-amd64
```

**Whether you've configured kube-proxy for iptables or ipvs mode**
```
$ kubectl -n kube-system logs kube-proxy-9jxfn
...
server_others.go:149] Using iptables Proxier.
...
```

### PR DESCRIPTION
**Pull request by johanfleury**
Fixes #499.

### CODE REVIEW

**Comment by danderson** [comment]
Tests are sad: https://circleci.com/gh/danderson/metallb/293?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification . I can patch it later, but if you have time to tweak the new IP range in the test (it's overlapping with the /25 above), that would be great :)

**Comment by danderson** [comment]
... Okay, well, now the tests pass on my local machine, but CircleCI is still failing...

**Comment by danderson** [comment]
Fixed for realz.

**Comment by johanfleury** [comment]
Thank you very much for your reactivity!

**Pull request merged**
