### PR TITLE
bgp: add support for non-RFC4893 (4 byte ASN)-compliant speakers

### PR DESCRIPTION
**Pull request by q3k**
This allows metallb to talk to older devices that might not support RFC4893. Previously the metallb speaker would always send 4-byte wide ASN paths, causing the other side to send a notification code 0x030b (Malformed AS_PATH). This fixes the issue by making the BGP session aware of 4-byte ASN capability and formatting UPDATE messages accordingly.

tcpdump showing bug:

```
OPEN from metallb:

185.236.240.39.55817 > 185.236.240.33.179: Flags [P.], cksum 0x547a (incorrect -> 0x4a5b), seq 1:50, ack 1, win 502, options [nop,nop,TS val 4202364832 ecr 1885893542], length 49: BGP
	Open Message (1), length: 49
	  Version 4, my AS 65002, Holdtime 90s, ID 185.236.240.39
	  Optional parameters, length: 20
	    Option Capabilities Advertisement (2), length: 18
	      Multiprotocol Extensions (1), length: 4
		AFI IPv4 (1), SAFI Unicast (1)
		0x0000:  0001 0001
	      Multiprotocol Extensions (1), length: 4
		AFI IPv6 (2), SAFI Unicast (1)
		0x0000:  0002 0001
	      32-Bit AS Number (65), length: 4
		 4 Byte AS 65002
		0x0000:  0000 fdea

OPEN from legacy device:

    185.236.240.33.179 > 185.236.240.39.55817: Flags [P.], cksum 0x9742 (correct), seq 1:44, ack 50, win 114, options [nop,nop,TS val 1885893545 ecr 4202364832], length 43: BGP
	Open Message (1), length: 43
	  Version 4, my AS 65001, Holdtime 180s, ID 185.236.240.64
	  Optional parameters, length: 14
	    Option Capabilities Advertisement (2), length: 12
	      Multiprotocol Extensions (1), length: 4
		AFI IPv4 (1), SAFI Unicast (1)
		0x0000:  0001 0001
	      Route Refresh (2), length: 0
	      Graceful Restart (64), length: 2
		Restart Flags: [none], Restart Time 180s
		0x0000:  00b4

UPDATE from metallb with broken, 4-byte AS path:

    185.236.240.39.55817 > 185.236.240.33.179: Flags [P.], cksum 0x5479 (incorrect -> 0xf6cd), seq 69:117, ack 63, win 502, options [nop,nop,TS val 4202364845 ecr 1885893545], length 48: BGP
	Update Message (2), length: 48
	  Origin (1), length: 1, Flags [T]: Incomplete
	    0x0000:  02
	  AS Path (2), length: 6, Flags [T]: 65002 
	    0x0000:  0201 0000 fdea
	  Next Hop (3), length: 4, Flags [T]: 185.236.240.39
	    0x0000:  b9ec f027
	  Updated routes:
	    185.236.240.112/32

NOTIFICATION from legacy device:

185.236.240.33.179 > 185.236.240.39.55817: Flags [P.], cksum 0x08ec (correct), seq 63:84, ack 117, win 114, options [nop,nop,TS val 1885893552 ecr 4202364845], length 21: BGP
	Notification Message (3), length: 21, UPDATE Message Error (3), subcode Malformed AS_PATH (11)
```

May I also interest you in using https://github.com/bio-routing/bio-rd ? :)

### CODE REVIEW

**Comment by q3k** [comment]
@danderson: friendly ping. Is there something missing from this PR before it can be reviewed/merged?

**Comment by q3k** [comment]
In this case this router isn't on the internet, it's a ToR datacenter switch that runs on a private ASN, that then only talks to our real internet edge router. And yes, I agree, this shouldn't be the case - but when you run infrastructure at a hackerspace, you make do with what you have ^^.

**Comment by hibby50** [comment]
Is there configuration that needs to be done in the yaml in order to take advantage of this functionality that I may be missing?

**Comment by johananl** [comment]
@hibby50 this has been merged before I joined the project so I could be wrong here, but it looks to me like this functionality has never been exposed at the config level. Here is where we construct BGP sessions:

https://github.com/metallb/metallb/blob/8f2f56213d89765c6c2e541c87eb5fdf13c3e6f6/internal/bgp/bgp.go#L355-L366

We aren't setting the `peerFBASNSupport` field.

Great catch! I've opened https://github.com/metallb/metallb/issues/734 to fix this.

**Comment by q3k** [comment]
@hibby50 This functionality (_not_ using 4-byte ASNs) should be automatically enabled when the other side doesn't state that it supports RFC 4893 in its OPEN message (capability code 65). I've also left a comment in #734 about this, let's carry on the discussion there.

**Pull request merged**
